version: 2

project_name: apisix-acme-go

builds:
  - id: main
    main: ./cmd/apisix-acme
    binary: apisix-acme
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: release-archive
    builds:
      - main
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: as7446
    name: apisix-acme-go
